version: 2
jobs:
  build:
    working_directory: ~/circlecipractice
    docker:
    - image: selenium/standalone-chrome:3.1.0
    steps:
    - run:
          name: Run Automation
          command: mvn clean test -DargLine="-Dspring.profiles.active=local" -Dcucumber.options="--tags @Smoke" -Dbrowser=chrome
    