# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

defaults: &defaults
  working_directory: ~/saved-searches-service
  docker:
    - image: circleci/openjdk:8-jdk
    
version: 2
jobs:
  build:
  
    <<: *defaults

    steps:
      - checkout
      - setup_remote_docker


      - run:
          name: Start Selenium
          command: |
            docker run -d -p 4444:4444 selenium/standalone-chrome:3.1.0
            sleep 45
		  

      - run:
          name: Automation tests
          command: mvn test -DargLine="-Dspring.profiles.active=ci" -Dcucumber.options="--tags @Smoke" -Dbrowser=chrome
