# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

defaults: &defaults
  working_directory: ~/saved-searches-service
  docker:
    - image: circleci/openjdk:8-jdk
    
version: 2
jobs:
  build:
  
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Automation tests
          command: mvn test -DargLine="-Dspring.profiles.active=ci" -Dcucumber.options="--tags @Smoke" -Dbrowser=chrome
