# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

defaults: &defaults
  working_directory: ~/automation-qa

version: 2
jobs:
  build: 
    
    <<: *defaults
    
    docker:
      - image: circleci/openjdk:8-jdk
      - image: selenium/standalone-chrome

    steps:
      - checkout

      - run:
          name: Automation tests
          command: mvn test -DargLine="-Dspring.profiles.active=ci" -Dcucumber.options="--tags @Smoke" -Dbrowser=chrome
  
#  automation_chrome:
#
#    <<: *defaults
#
#    docker:
#      - image: circleci/openjdk:8-jdk
#      - image: selenium/standalone-chrome
#
#    steps:
#      - checkout
#
#      - run:
#          name: Automation tests
#          command: mvn test -DargLine="-Dspring.profiles.active=ci" -Dcucumber.options="--tags @Smoke" -Dbrowser=chrome

  automation_firefox:

    <<: *defaults

    docker:
      - image: circleci/openjdk:8-jdk
      - image: selenium/standalone-firefox

    steps:
      - checkout

      - run:
          name: Automation tests
          command: mvn test -DargLine="-Dspring.profiles.active=ci" -Dcucumber.options="--tags @Smoke" -Dbrowser=firefox

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build:
        filters:
          branches:
            only:Tese
#      - automation_chrome:
#        requires:
#          - build
      - automation_firefox:
        requires:
          - build
