version: 2
jobs:
  build:
    working_directory: ~/circlecipractice
    docker:
    - image: selenium/standalone-chrome:3.1.0
    - image: circleci/openjdk:8-jdk-browsers
    steps:
    - run:
        name: Run Automation
        command: test -DargLine="-Dspring.profiles.active=local" -Dcucumber.options="--tags @Smoke" -Dbrowser=chrome
        test:
  override:
    - mkdir -p $CIRCLE_TEST_REPORTS/cucumber
    - bundle exec cucumber --format junit --out $CIRCLE_TEST_REPORTS/cucumber/junit.xml