version: 2
jobs:
  build:
    
    working_directory: ~/circlecipractice

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      
    steps:
      - run: mvn clean test -DargLine="-Dspring.profiles.active=ci" -Dcucumber.options="--tags @Smoke" -Dbrowser=chrome
      - run: |
          mkdir -p $CIRCLE_TEST_REPORTS/cucumber
          bundle exec cucumber --format pretty --format json --out $CIRCLE_TEST_REPORTS/cucumber/tests.cucumber