# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

defaults: &defaults
  working_directory: ~/automation-qa

version: 2
jobs:
  automation_chrome:

    <<: *defaults

    docker:
      - image: circleci/openjdk:8-jdk
      - image: selenium/standalone-chrome

    steps:
      - checkout

      - run:
          name: Automation tests
          command: mvn test -DargLine="-Dspring.profiles.active=ci" -Dcucumber.options="--tags @Smoke" -Dbrowser=chrome

  automation_firefox:

    <<: *defaults

    docker:
      - image: circleci/openjdk:8-jdk
      - image: selenium/standalone-firefox

    steps:
      - checkout

      - run:
          name: Automation tests
          command: mvn test -DargLine="-Dspring.profiles.active=ci" -Dcucumber.options="--tags @Smoke" -Dbrowser=firefox

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - automation_chrome:
        filters:
          branches: - only: master
      - automation_firefox:
        filters:
          branches:
            only: master
